---
- name: LINO Petstore Example
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}"
  vars:
    #  Business variables
    workspace: "example/petstore"
    source_db: "postgresql://localhost:5432/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"
    target_db: "postgresql://localhost:5433/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"

    ### fifo files
    fifo_pets: "/tmp/pets.jsonl"
    fifo_owners: "/tmp/owners.jsonl"
    fifo_pets_masking: "/tmp/pets-masking.jsonl"

  tasks:

    - name: Deploy example's stack with Docker Compose
      # become: true
      community.docker.docker_compose_v2:
        project_src: "{{ workspace }}"
        files:
          - docker-compose.yml  # You can stack multiple files
        state: present
        wait: true                   # Wait for containers to be healthy
        # build: never                 # Use 'always' if you want to force image builds
      register: compose_output

    - name: Debug compose status
      debug:
        var: compose_output.actions


    # Check connections and initialize FIFOs
    - include_role: { name: OB-Live.nino, tasks_from: connect }

    - include_role: { name: OB-Live.nino, tasks_from: fifos }
      loop:
        - "{{ fifo_pets_masking }}"
        - "{{ fifo_pets }}"
        - "{{ fifo_owners }}"

    # Business logic here
    # Owners
    - include_role: { name: OB-Live.nino, tasks_from: push } # declare push
      vars:
        idName: "owners"
        pipeIn: "{{ fifo_owners }}"

    - include_role: { name: OB-Live.nino, tasks_from: pull } # then pull
      vars:
        idName: "owners"
        pipeOut: "{{ fifo_owners }}"

    # Pets
    - include_role: { name: OB-Live.nino, tasks_from: push }
      vars:
        idName: "pets"
        pipeIn: "{{ fifo_pets_masking }}"

    - include_role: { name: OB-Live.nino, tasks_from: mask }
      vars:
        idName: "pets"
        pipeIn: "{{ fifo_pets }}"
        pipeOut: "{{ fifo_pets_masking }}"
        masking: "{{ workspace }}/target/pets-masking.yml"

    - include_role: { name: OB-Live.nino, tasks_from: pull }
      vars:
        idName: "pets"
        pipeOut: "{{ fifo_pets }}"
