---
- name: LINO Petstore Example
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_dir }}"
    ADMIN: admin
  vars:
    #  Business variables
    workspace: "example/petstore"
    # golang_download_dir: /tmp
    source_db: "postgresql://localhost:5432/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"
    target_db: "postgresql://localhost:5433/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"

    ### fifo files
    fifos_dir: "/tmp/lino"
    fifo_pets: "{{ fifos_dir }}/pets.jsonl"
    fifo_owners: "{{ fifos_dir }}/owners.jsonl"
    fifo_pets_masking: "{{ fifos_dir }}/pets-masking.jsonl"

  tasks:

    - name: Deploy example's stack with Docker Compose
      # become: true
      community.docker.docker_compose_v2:
        project_src: "{{ workspace }}"
        files:
          - docker-compose.yml  # You can stack multiple files
        state: present
        wait: true                   # Wait for containers to be healthy
        # build: never                 # Use 'always' if you want to force image builds
      register: compose_output

    - name: Debug compose status
      debug:
        var: compose_output.actions

    #### BUSINESS LOGIC HERE ####
    # Check connections and initialize FIFOs
    - include_role: { name: OB-Live.nino, tasks_from: connect } 
      vars:
        workspace: "example/petstore"

    - include_role: { name: OB-Live.nino, tasks_from: fifos }
      loop:
        - "{{ fifo_pets_masking }}"
        - "{{ fifo_pets }}"
        - "{{ fifo_owners }}"


    # Owners (declare push, then pull)
    - include_role: { name: OB-Live.nino, tasks_from: push } # declare push 
      vars:
        idName: "owners" 

    - include_role: { name: OB-Live.nino, tasks_from: pull } # then pull 
      vars:
        idName: "owners"
        workspace: "example/petstore"

    # Pets (declare push, then declare mask, then pull)
    - include_role: { name: OB-Live.nino, tasks_from: push } # declare push 
      vars:
        idName: "pets"
        pipeIn: "{{ fifo_pets_masking }}"

    - include_role: { name: OB-Live.nino, tasks_from: mask }  # then declare mask  
      vars:
        idName: "pets" 

    - include_role: { name: OB-Live.nino, tasks_from: pull } # then pull 
      vars:
        idName: "pets" 
