---
- name: LINO Petstore Example 
  hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    #  Business case variables
    workspace: "example/petstore" 
    source_db: "postgresql://localhost:5432/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"
    target_db: "postgresql://localhost:5433/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"

    ### fifo files
    fifo_pets: "/tmp/pets.jsonl"
    fifo_owners: "/tmp/owners.jsonl"
    fifo_pets_masking: "/tmp/pets-masking.jsonl"

  tasks:
    - include_role:
        name: OB-Live.nino
        tasks_from: install

    - include_role:
        name: OB-Live.nino
        tasks_from: connect
      # vars:
      #   source_db: "postgresql://localhost:5432/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"
      #   target_db: "postgresql://localhost:5433/jhpetclinic?sslmode=disable -P ADMIN -u jhpetclinic"

    - include_role:
        name: OB-Live.nino
        tasks_from: fifos
      loop:
        - "{{ fifo_pets_masking }}"
        - "{{ fifo_pets }}"
        - "{{ fifo_owners }}"

    # Owners
    - include_role:
        name: OB-Live.nino
        tasks_from: pull
      vars:
        idName: "owners"
        pipeOut: "owners.jsonl"

    - include_role:
        name: OB-Live.nino
        tasks_from: push
      vars:
        idName: "owners"
        pipeIn: "owners.jsonl"

    # Pets
    - include_role:
        name: OB-Live.nino
        tasks_from: pull
      vars:
        idName: "pets"
        pipeOut: "pets.jsonl"

    - include_role:
        name: OB-Live.nino
        tasks_from: push
      vars:
        idName: "pets"
        pipeIn: "pets.jsonl"

    - name: Verify the results
      debug:
        msg: "Content of README.md has been sent through pipes to target db"