---
# Cleanup and report
# - name: Check if the long-running job is done and cleanup
#   ansible.builtin.async_status:
#     jid: "{{ async_job_result.ansible_job_id }}"
#     mode: cleanup
#   ignore_errors: true

- name: Stop all running Lino processes
  # Using command with pgrep and xargs to avoid shell-specific warnings
  ansible.builtin.command: "pgrep -f 'lino' | xargs kill"
  # become: true
  failed_when: false # Don't fail if no process is found
  changed_when: false