---
- name: Clear dataconnctor.yaml
  ansible.builtin.command: rm -f dataconnctor.yaml
  changed_when: false

- name: "LINO Connect source : {{ source_db }}"
  ansible.builtin.shell: |
    echo "$ lino dc add source {{ source_db }}" >> exec.log
    lino dc add source {{ source_db }} &>> exec.log

    echo "$ lino dc ping source" >> exec.log
    lino dc ping source &>> exec.log

    echo "$ lino table extract source" >> exec.log
    lino table extract source &>> exec.log

    echo "$ lino relation extract source" >> exec.log
    lino relation extract source &>> exec.log

    echo "$ lino analyse source > {{ workspace }}/source/analyze.yml" >> exec.log
    lino analyse source > {{ workspace }}/source/analyze.yml
  args:
    executable: /bin/bash
  register: connectsrc_result
  changed_when: "connectsrc_result.rc != 0"

- name: "LINO Connect target : {{ target_db }}"
  ansible.builtin.shell: |
    echo "$ lino dc add target {{ target_db }}" >> exec.log
    lino dc add target {{ target_db }} &>> exec.log

    echo "$ lino dc ping target" >> exec.log
    lino dc ping target &>> exec.log
  args:
    executable: /bin/bash
  register: connecttgt_result
  changed_when: "connecttgt_result.rc != 0"

- name: "LINO Extract metadata"
  block:
    - name: "Extract metadata"
      ansible.builtin.shell: |
        echo "$ lino id create {{ item }} -i {{ descriptor }}" >> exec.log
        lino id create {{ item }} -i {{ descriptor }} &>> exec.log

        echo "$ lino id display-plan -i {{ descriptor }}" >> exec.log
        lino id display-plan -i {{ descriptor }} &>> exec.log
      args:
        executable: /bin/bash
      register: extract_result
      changed_when: "extract_result.rc != 0"
      vars:
        descriptor: "{{ workspace }}/source/{{ item }}-descriptor.yml"
        # data_out: "business/{{ id_name }}_data.jsonl"
      loop:
        - 'owners'
        - 'pets'

    - name: "Log - Connecting and Extracting metadata"
      ansible.builtin.debug:
        msg:
          - "{{ connectsrc_result.stdout_lines }}"
          - "{{ connecttgt_result.stdout_lines }}"
          - "{{ extract_result }}"
