---
- name: Clear the named pipes {{ item }}
  ansible.builtin.command: |
    echo  "rm -f {{ item }} " > exec.log
    rm -f {{ item }}
  changed_when: false

- name: Create the named pipe {{ item }}
  ansible.builtin.command: |
    echo  "mkfifo --m 666 {{ item }} " > exec.log
    mkfifo --m 666 {{ item }}
  args:
    creates: "{{ item }}"