---


- name: "PIMO Masking : {{ id_name }}"
  shell: |
    echo "$ nohup pimo -c {{ masking }} < {{ pipeIn }} > {{ pipeOut }} 2>&1 & " >> exec.log
    nohup pimo -c {{ masking }} < {{ pipeIn }} > {{ pipeOut }} 2>&1 &
    echo $! >> exec.log
  args:
    executable: /bin/bash
  register: mask_result
  vars:
    masking: "{{ workspace }}/target/{{ id_name }}-masking.yml"
    pipeIn: "{{ fifos_dir }}/{{ id_name }}.jsonl"
    pipeOut: "{{ fifos_dir }}/{{ id_name }}-masking.jsonl"
  when: masking_file.stat.exists

# - name: "Log - Masking : {{ id_name }}"
#   debug:
#     msg:
#       - "{{mask_result.cmd}}"
#       - "{{mask_result.stdout_lines}}"
#   when: masking_file.stat.exists