---
- name: "Execute LINO Pull : {{ id_name }}"
  shell: |
    echo "$ lino pull source -l 10 -i {{ descriptor }} > {{ pipeOut }}" &>> exec.log
    lino pull source -l 10 -i {{ descriptor }} > {{ pipeOut }}
  args:
    executable: /bin/bash
  # register: pull_result
  vars:
    descriptor: "{{ workspace }}/target/{{ id_name }}-descriptor.yml"
    pipeOut: "{{ fifos_dir }}/{{ id_name }}.jsonl"
   

# - name: "Log - Pull : {{ id_name }}"
#   debug:
#     var: pull_result
