---
- name: "Execute LINO Pull : {{ id_name }}"
  ansible.builtin.shell: |
    echo "$ lino pull source -l 10 -i {{ descriptor }} > {{ pipe_out }}" &>> exec.log
    lino pull source -l 10 -i {{ descriptor }} > {{ pipe_out }}
  args:
    executable: /bin/bash
  # register: pull_result
  vars:
    descriptor: "{{ workspace }}/target/{{ id_name }}-descriptor.yml"
    pipe_out: "{{ fifos_dir }}/{{ id_name }}.jsonl"
   

# - name: "Log - Pull : {{ id_name }}"
#   debug:
#     var: pull_result
