---
- name: "Declare LINO Push : {{ id_name }}"
  ansible.builtin.shell: |
    echo "$ nohup lino push target -v5 -i {{ descriptor }} < {{ pipe_in }} 2>&1 & " >> exec.log
    nohup lino push target -v5 -i {{ descriptor }} < {{ pipe_in }} 2>&1 &
    echo $! >> exec.log
  args:
    executable: /bin/bash
  register: push_result
  changed_when: false
  vars:
    descriptor: "{{ workspace }}/target/{{ id_name }}-descriptor.yml"
    pipe_in: "{{ fifos_dir }}/{{ id_name }}.jsonl"
  async: 10
  poll: 0

# - name: "Log - Push : {{ id_name }}"
#   debug:
#     var: push_result
