---
- name: "LINO Truncate target : {{ id_name }}"
  when: truncate_target | default(false)
  ansible.builtin.shell: |
    echo "$ lino pull target -i {{ descriptor }} " >> exec.log
    lino pull target -i {{ descriptor }} >> exec.log

    echo "$ lino push truncate target -i {{ descriptor }} " >> exec.log
    lino push truncate target -i {{ descriptor }} </dev/null

    echo "$ lino pull target -i {{ descriptor }} " >> exec.log
    lino pull target -i {{ descriptor }} >> exec.log
  args:
    executable: /bin/bash
  changed_when: false
  vars:
    descriptor: "{{ workspace }}/target/{{ id_name }}-descriptor.yaml"
